export const NanoEvents = {
  // Core Events
  COMMAND_RECEIVED: 'COMMAND_RECEIVED',
  EXECUTE_TERMINAL: 'EXECUTE_TERMINAL',
  JOB_COMPLETED: 'JOB_COMPLETED',
  JOB_FAILED: 'JOB_FAILED',
  TERMINAL_RESULT: 'TERMINAL_RESULT',
  TERMINAL_ERROR: 'TERMINAL_ERROR',
  KICK_QUEUE: 'KICK_QUEUE',

  // Tool Specific Events (Terminal Results)
  AMASS_TERMINAL_RESULT: 'AMASS_TERMINAL_RESULT',
  AMASS_TERMINAL_ERROR: 'AMASS_TERMINAL_ERROR',

  SUBFINDER_TERMINAL_RESULT: 'SUBFINDER_TERMINAL_RESULT',
  SUBFINDER_TERMINAL_ERROR: 'SUBFINDER_TERMINAL_ERROR',

  NSLOOKUP_TERMINAL_RESULT: 'NSLOOKUP_TERMINAL_RESULT',
  NSLOOKUP_TERMINAL_ERROR: 'NSLOOKUP_TERMINAL_ERROR',

  NMAP_TERMINAL_RESULT: 'NMAP_TERMINAL_RESULT',
  NMAP_TERMINAL_ERROR: 'NMAP_TERMINAL_ERROR',

  RUSTSCAN_TERMINAL_RESULT: 'RUSTSCAN_TERMINAL_RESULT',
  RUSTSCAN_TERMINAL_ERROR: 'RUSTSCAN_TERMINAL_ERROR',

  GOBUSTER_RESULT: 'GOBUSTER_RESULT',
  GOBUSTER_ERROR: 'GOBUSTER_ERROR',

  ENUM4LINUX_TERMINAL_RESULT: 'ENUM4LINUX_TERMINAL_RESULT',
  ENUM4LINUX_TERMINAL_ERROR: 'ENUM4LINUX_TERMINAL_ERROR',

  FFUF_RESULT: 'FFUF_RESULT',
  FFUF_ERROR: 'FFUF_ERROR',

  WHATWEB_RESULT: 'WHATWEB_RESULT',
  WHATWEB_ERROR: 'WHATWEB_ERROR',

  DNSENUM_TERMINAL_RESULT: 'DNSENUM_TERMINAL_RESULT',
  DNSENUM_TERMINAL_ERROR: 'DNSENUM_TERMINAL_ERROR',
} as const;

export type NanoEventKey = keyof typeof NanoEvents;
